default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dc_widget_app_development

test:
  <<: *default
  database: dc_widget_app_test

production:
  <<: *default
  database: dc_widget_app